# Generated by Django 4.2.25 on 2025-10-02 16:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Excluído em')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
                ('numero', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Número do Pedido')),
                ('cliente_nome', models.CharField(max_length=255, verbose_name='Nome do Cliente')),
                ('cliente_telefone', models.CharField(max_length=20, verbose_name='Telefone do Cliente')),
                ('cliente_email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail do Cliente')),
                ('cliente_cpf', models.CharField(blank=True, max_length=14, verbose_name='CPF do Cliente')),
                ('endereco_cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('endereco_logradouro', models.CharField(max_length=255, verbose_name='Logradouro')),
                ('endereco_numero', models.CharField(max_length=20, verbose_name='Número')),
                ('endereco_complemento', models.CharField(blank=True, max_length=100, verbose_name='Complemento')),
                ('endereco_bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('endereco_cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('endereco_estado', models.CharField(max_length=2, verbose_name='Estado')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONFIRMADO', 'Confirmado'), ('PREPARANDO', 'Preparando'), ('PRONTO', 'Pronto para Entrega'), ('SAIU_ENTREGA', 'Saiu para Entrega'), ('ENTREGUE', 'Entregue'), ('CANCELADO', 'Cancelado')], db_index=True, default='PENDENTE', max_length=20, verbose_name='Status')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Subtotal')),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Desconto')),
                ('frete', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Frete')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('observacoes_internas', models.TextField(blank=True, verbose_name='Observações Internas')),
                ('data_entrega_prevista', models.DateTimeField(blank=True, null=True, verbose_name='Data de Entrega Prevista')),
                ('data_entrega_realizada', models.DateTimeField(blank=True, null=True, verbose_name='Data de Entrega Realizada')),
                ('cliente_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_cliente', to=settings.AUTH_USER_MODEL, verbose_name='Cliente (Usuário)')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_vendedor', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StatusHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('status_anterior', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONFIRMADO', 'Confirmado'), ('PREPARANDO', 'Preparando'), ('PRONTO', 'Pronto para Entrega'), ('SAIU_ENTREGA', 'Saiu para Entrega'), ('ENTREGUE', 'Entregue'), ('CANCELADO', 'Cancelado')], max_length=20, verbose_name='Status Anterior')),
                ('status_novo', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONFIRMADO', 'Confirmado'), ('PREPARANDO', 'Preparando'), ('PRONTO', 'Pronto para Entrega'), ('SAIU_ENTREGA', 'Saiu para Entrega'), ('ENTREGUE', 'Entregue'), ('CANCELADO', 'Cancelado')], max_length=20, verbose_name='Status Novo')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_status', to='pedidos.pedido', verbose_name='Pedido')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Histórico de Status',
                'verbose_name_plural': 'Históricos de Status',
                'db_table': 'status_historico',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('quantidade', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço Unitário')),
                ('preco_total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço Total')),
                ('variacao', models.CharField(blank=True, max_length=255, verbose_name='Variação')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='pedidos.pedido', verbose_name='Pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Item do Pedido',
                'verbose_name_plural': 'Itens dos Pedidos',
                'db_table': 'itens_pedido',
            },
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['vendedor', 'status'], name='pedidos_vendedo_da19a4_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['status', 'created_at'], name='pedidos_status_6c74e6_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['numero'], name='pedidos_numero_107754_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='itempedido',
            unique_together={('pedido', 'produto', 'variacao')},
        ),
    ]
