# Generated by Django 4.2.25 on 2025-10-03 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_whatsapp', models.CharField(blank=True, max_length=30, verbose_name='Número do WhatsApp')),
                ('nome_empresa', models.CharField(blank=True, max_length=255, verbose_name='Nome da Empresa')),
                ('mensagem_pedido', models.TextField(blank=True, verbose_name='Mensagem de Pedido')),
                ('mensagem_entrega', models.TextField(blank=True, verbose_name='Mensagem de Entrega')),
                ('enviar_pedido', models.BooleanField(default=True, verbose_name='Enviar ao criar pedido')),
                ('enviar_entrega', models.BooleanField(default=True, verbose_name='Enviar ao despachar pedido')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_settings', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Configuração de WhatsApp',
                'verbose_name_plural': 'Configurações de WhatsApp',
                'db_table': 'whatsapp_settings',
            },
        ),
    ]
