# Generated by Django 4.2.25 on 2025-10-02 16:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Excluído em')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='categorias/', verbose_name='Imagem')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='produtos.categoria', verbose_name='Categoria Pai')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'categorias',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Excluído em')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
                ('nome', models.CharField(db_index=True, max_length=255, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('descricao_curta', models.CharField(blank=True, max_length=255, verbose_name='Descrição Curta')),
                ('preco', models.DecimalField(db_index=True, decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço')),
                ('preco_promocional', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço Promocional')),
                ('estoque', models.IntegerField(db_index=True, default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Estoque')),
                ('estoque_minimo', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Estoque Mínimo')),
                ('codigo', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Código')),
                ('sku', models.CharField(blank=True, max_length=50, verbose_name='SKU')),
                ('ean', models.CharField(blank=True, max_length=13, verbose_name='EAN')),
                ('marca', models.CharField(blank=True, max_length=100, verbose_name='Marca')),
                ('disponivel', models.BooleanField(db_index=True, default=True, verbose_name='Disponível')),
                ('em_destaque', models.BooleanField(db_index=True, default=False, verbose_name='Em Destaque')),
                ('em_promocao', models.BooleanField(db_index=True, default=False, verbose_name='Em Promoção')),
                ('mais_vendido', models.BooleanField(db_index=True, default=False, verbose_name='Mais Vendido')),
                ('lancamento', models.BooleanField(db_index=True, default=False, verbose_name='Lançamento')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Peso (kg)')),
                ('altura', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Altura (cm)')),
                ('largura', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Largura (cm)')),
                ('comprimento', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Comprimento (cm)')),
                ('visualizacoes', models.IntegerField(default=0, verbose_name='Visualizações')),
                ('vendas', models.IntegerField(default=0, verbose_name='Vendas')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='produtos.categoria', verbose_name='Categoria')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'db_table': 'produtos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImagemProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('imagem', models.ImageField(upload_to='produtos/imagens/', verbose_name='Imagem')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='produtos/thumbnails/', verbose_name='Thumbnail')),
                ('is_principal', models.BooleanField(default=False, verbose_name='Imagem Principal')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='Texto Alternativo')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='produtos.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Imagem do Produto',
                'verbose_name_plural': 'Imagens dos Produtos',
                'db_table': 'imagens_produto',
                'ordering': ['ordem', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProdutoVariacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Variação')),
                ('valor', models.CharField(max_length=100, verbose_name='Valor')),
                ('preco_adicional', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço Adicional')),
                ('estoque', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Estoque')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variacoes', to='produtos.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Variação do Produto',
                'verbose_name_plural': 'Variações dos Produtos',
                'db_table': 'produto_variacoes',
                'unique_together': {('produto', 'nome', 'valor')},
            },
        ),
        migrations.CreateModel(
            name='ProdutoAtributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Atributo')),
                ('valor', models.CharField(max_length=255, verbose_name='Valor')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atributos', to='produtos.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Atributo do Produto',
                'verbose_name_plural': 'Atributos dos Produtos',
                'db_table': 'produto_atributos',
                'unique_together': {('produto', 'nome')},
            },
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['vendedor', 'is_active'], name='produtos_vendedo_31a2b5_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['categoria', 'is_active'], name='produtos_categor_472db2_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['preco'], name='produtos_preco_7f62fb_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['estoque'], name='produtos_estoque_6863c0_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['codigo'], name='produtos_codigo_2217c3_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['em_destaque', 'is_active'], name='produtos_em_dest_62c36b_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['disponivel', 'is_active'], name='produtos_disponi_b9f31f_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['em_promocao', 'is_active'], name='produtos_em_prom_f16b51_idx'),
        ),
        migrations.AddIndex(
            model_name='categoria',
            index=models.Index(fields=['slug'], name='categorias_slug_e69df5_idx'),
        ),
        migrations.AddIndex(
            model_name='categoria',
            index=models.Index(fields=['is_active', 'ordem'], name='categorias_is_acti_65b596_idx'),
        ),
    ]
