# Generated by Django 4.2.25 on 2025-10-02 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("produtos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subcategoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Criado em"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Excluído em"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Ativo"
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="Nome")),
                ("slug", models.SlugField(max_length=100, verbose_name="Slug")),
                ("descricao", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "imagem",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="subcategorias/",
                        verbose_name="Imagem",
                    ),
                ),
                ("ordem", models.IntegerField(default=0, verbose_name="Ordem")),
            ],
            options={
                "verbose_name": "Subcategoria",
                "verbose_name_plural": "Subcategorias",
                "db_table": "subcategorias",
                "ordering": ["categoria__ordem", "categoria__nome", "ordem", "nome"],
            },
        ),
        migrations.RemoveField(
            model_name="categoria",
            name="parent",
        ),
        migrations.AddField(
            model_name="subcategoria",
            name="categoria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategorias",
                to="produtos.categoria",
                verbose_name="Categoria",
            ),
        ),
        migrations.AddField(
            model_name="produto",
            name="subcategoria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="produtos",
                to="produtos.subcategoria",
                verbose_name="Subcategoria",
            ),
        ),
        migrations.AddIndex(
            model_name="produto",
            index=models.Index(
                fields=["subcategoria", "is_active"], name="produtos_subcate_118aa4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subcategoria",
            index=models.Index(
                fields=["categoria", "slug"], name="subcategori_categor_82b4bd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subcategoria",
            index=models.Index(
                fields=["is_active", "ordem"], name="subcategori_is_acti_d3b8d1_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="subcategoria",
            unique_together={("categoria", "slug")},
        ),
    ]
