# Generated by Django 4.2.25 on 2025-10-02 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_subcategoria_remove_categoria_parent_and_more'),
    ]

    operations = [
    ]
