# Generated by Django 4.2.25 on 2025-10-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_auto_20251002_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='altura',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='comprimento',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='largura',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='peso',
        ),
        migrations.AlterField(
            model_name='produto',
            name='codigo',
            field=models.CharField(blank=True, db_index=True, max_length=50, unique=True, verbose_name='Código'),
        ),
    ]
