# Generated by Django 4.2.25 on 2025-10-02 20:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_remove_produto_altura_remove_produto_comprimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='estoque_minimo',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Estoque Mínimo'),
        ),
    ]
