# Generated by Django 4.2.25 on 2025-10-02 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_alter_produto_estoque_minimo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='estoque_minimo',
        ),
    ]
